version: '3.8'

services:
  mysql:
    image: mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    volumes:
      - data:/var/lib/mysql
  cat-db:
    depends_on:
      - mysql
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 80:80
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
    stdin_open: true
    tty: true
    volumes:
      - images:/home/node/app/images
volumes:
  data:
  images: