version: '3.8'

services:
  mysql:
    image: mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    volumes:
      - data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      retries: 10
  cat-db:
    depends_on:
      mysql:
        condition: service_healthy
    build:
      context: .
      args:
        HTTP_PROXY: $HTTP_PROXY
        HTTPS_PROXY: $HTTPS_PROXY
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 80:80
    environment:
      - DB_HOST=mysql
      - DB_USER=root
    stdin_open: true
    tty: true
    volumes:
      - images:/home/node/app/images
volumes:
  data:
  images:
