version: '3.8'

services:
  mysql:
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    volumes:
      - data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
  cat-service:
    depends_on:
      mysql:
        condition: service_healthy
    build:
      context: cat-service
      args:
        HTTP_PROXY: $HTTP_PROXY
        HTTPS_PROXY: $HTTPS_PROXY
    restart: unless-stopped
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
    healthcheck:
      test: ["CMD", "curl", "localhost"]
      interval: 10s
    ports:
      - 80:80
    volumes:
      - images:/home/node/app/images
volumes:
  data:
  images:
